### ISSUE TITLE
Minor tweaks to localsys

### ISSUE THREAD

**Issue by dmolik** [jhunt/clockwork#17]
- [x] For Gentoo, eix-sync should be run outside of clockwork, or scheduled via cron or another mechanism inside of Clockwork, just not via the localsys file.
- [x] By default OpenRC no longer provides a link from /sbin/rc-service to /sbin/service, localsys should reflect this.
- [ ] Functionality should probably be split out via package managers and init systems, not via distro, thus OpenRC could be utilized for Alpine Linux and Gentoo, and systemd could be utilized for Gentoo and RHEL distros. Etc.

**Comment by jhunt** [comment]
First one's fixed in #18, right?

**Comment by GrayTShirt** [comment]
yep.
